name: Publish On 'release' commit

on:
  push:
    branches: 
      - 'main'

jobs:
  check_commit_message:
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check commit message
        continue-on-error: true
        run: |
          commit_message=$(git log -1 --pretty=format:%s)
          echo "Commit message: $commit_message"
          if [[ "$commit_message" != release* ]]; then
            echo "Commit message does not start with 'release', stopping workflow."
            exit 1
          fi
  publish:
    needs: check_commit_message
    if: needs.check_commit_message.outputs.status == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0 # Fetches all history (and tags) for all branches and tags
          persist-credentials: false
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'
    - run: npm i
  # - run: npm run lint
    - run: npm run build
  # - run: npm run test
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
