name: Publish

on:
  branches: 
    - 'main'

jobs:
  check_commit_message:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 2 # Fetches only the last two commits to speed up the process
        - name: Check commit message
          id: check_message
          run: |
            commit_message=$(git log -1 --pretty=format:%s)
            echo "Commit message: $commit_message"
            if [[ $commit_message == release* ]]; then
              echo "Proceeding with publishing steps."
              echo "proceed_with_publishing=true" >> $GITHUB_ENV
            else
              echo "Commit does not start with 'release', skipping publishing steps."
              echo "proceed_with_publishing=false" >> $GITHUB_ENV
  publish:
    needs: check_commit_message
    if: env.proceed_with_publishing == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        with:
        fetch-depth: 0 # Fetches all history (and tags) for all branches and tags
        persist-credentials: false
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Cache pnpm store
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - run: pnpm i
   # - run: pnpm run lint
    - run: pnpm run build
   # - run: pnpm run test
    - run: pnpm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
